<?php

namespace Database\Seeders;

use App\Models\Location;
use Illuminate\Database\Seeder;

class LocationSeeder extends Seeder
{
    public function run(): void
    {
        $locations = $this->getTunisianLocations();

        foreach ($locations as $locationData) {
            Location::updateOrCreate(
                ['code' => $locationData['code']],
                $locationData
            );
        }

        $this->command->info('✅ ' . count($locations) . ' locations seeded successfully!');
    }

    private function getTunisianLocations(): array
    {
        return [
            // Tunis (2 clinics)
            [
                'name' => ['fr' => 'Clinique Centre Ville Tunis', 'ar' => 'عيادة وسط مدينة تونس', 'en' => 'Tunis Downtown Clinic'],
                'code' => 'CLINIC-TUN-01',
                'email' => 'tunis.centre@clinicbooking.tn',
                'phone' => '+216 71 123 001',
                'address' => 'Avenue Habib Bourguiba',
                'city' => 'Tunis',
                'postal_code' => '1000',
                'country' => 'Tunisia',
                'latitude' => 36.8065,
                'longitude' => 10.1815,
                'timezone' => 'Africa/Tunis',
                'working_hours' => $this->getStandardWorkingHours(),
                'is_active' => true,
            ],
            [
                'name' => ['fr' => 'Clinique Lac Tunis', 'ar' => 'عيادة البحيرة تونس', 'en' => 'Tunis Lake Clinic'],
                'code' => 'CLINIC-TUN-02',
                'email' => 'tunis.lac@clinicbooking.tn',
                'phone' => '+216 71 123 002',
                'address' => 'Les Berges du Lac',
                'city' => 'Tunis',
                'postal_code' => '1053',
                'country' => 'Tunisia',
                'latitude' => 36.8372,
                'longitude' => 10.2461,
                'timezone' => 'Africa/Tunis',
                'working_hours' => $this->getStandardWorkingHours(),
                'is_active' => true,
            ],

            // Ariana (2 clinics)
            [
                'name' => ['fr' => 'Clinique Ariana Centre', 'ar' => 'عيادة أريانة المركز', 'en' => 'Ariana Center Clinic'],
                'code' => 'CLINIC-ARI-01',
                'email' => 'ariana.centre@clinicbooking.tn',
                'phone' => '+216 71 234 001',
                'address' => 'Avenue de la République',
                'city' => 'Ariana',
                'postal_code' => '2080',
                'country' => 'Tunisia',
                'latitude' => 36.8625,
                'longitude' => 10.1956,
                'timezone' => 'Africa/Tunis',
                'working_hours' => $this->getStandardWorkingHours(),
                'is_active' => true,
            ],
            [
                'name' => ['fr' => 'Clinique Soukra', 'ar' => 'عيادة السكرة', 'en' => 'Soukra Clinic'],
                'code' => 'CLINIC-ARI-02',
                'email' => 'soukra@clinicbooking.tn',
                'phone' => '+216 71 234 002',
                'address' => 'Route de la Soukra',
                'city' => 'Ariana',
                'postal_code' => '2036',
                'country' => 'Tunisia',
                'latitude' => 36.8500,
                'longitude' => 10.2100,
                'timezone' => 'Africa/Tunis',
                'working_hours' => $this->getStandardWorkingHours(),
                'is_active' => true,
            ],

            // Ben Arous (2 clinics)
            [
                'name' => ['fr' => 'Clinique Ben Arous', 'ar' => 'عيادة بن عروس', 'en' => 'Ben Arous Clinic'],
                'code' => 'CLINIC-BEN-01',
                'email' => 'benarous@clinicbooking.tn',
                'phone' => '+216 71 345 001',
                'address' => 'Avenue Farhat Hached',
                'city' => 'Ben Arous',
                'postal_code' => '2013',
                'country' => 'Tunisia',
                'latitude' => 36.7470,
                'longitude' => 10.2189,
                'timezone' => 'Africa/Tunis',
                'working_hours' => $this->getStandardWorkingHours(),
                'is_active' => true,
            ],
            [
                'name' => ['fr' => 'Clinique Ezzahra', 'ar' => 'عيادة الزهراء', 'en' => 'Ezzahra Clinic'],
                'code' => 'CLINIC-BEN-02',
                'email' => 'ezzahra@clinicbooking.tn',
                'phone' => '+216 71 345 002',
                'address' => 'Avenue de la Liberté',
                'city' => 'Ezzahra',
                'postal_code' => '2034',
                'country' => 'Tunisia',
                'latitude' => 36.7500,
                'longitude' => 10.3100,
                'timezone' => 'Africa/Tunis',
                'working_hours' => $this->getStandardWorkingHours(),
                'is_active' => true,
            ],

            // Manouba (2 clinics)
            [
                'name' => ['fr' => 'Clinique Manouba', 'ar' => 'عيادة منوبة', 'en' => 'Manouba Clinic'],
                'code' => 'CLINIC-MAN-01',
                'email' => 'manouba@clinicbooking.tn',
                'phone' => '+216 71 456 001',
                'address' => 'Avenue Habib Bourguiba',
                'city' => 'Manouba',
                'postal_code' => '2010',
                'country' => 'Tunisia',
                'latitude' => 36.8100,
                'longitude' => 10.0970,
                'timezone' => 'Africa/Tunis',
                'working_hours' => $this->getStandardWorkingHours(),
                'is_active' => true,
            ],
            [
                'name' => ['fr' => 'Clinique Denden', 'ar' => 'عيادة دندن', 'en' => 'Denden Clinic'],
                'code' => 'CLINIC-MAN-02',
                'email' => 'denden@clinicbooking.tn',
                'phone' => '+216 71 456 002',
                'address' => 'Route de Denden',
                'city' => 'Manouba',
                'postal_code' => '2086',
                'country' => 'Tunisia',
                'latitude' => 36.8300,
                'longitude' => 10.1200,
                'timezone' => 'Africa/Tunis',
                'working_hours' => $this->getStandardWorkingHours(),
                'is_active' => true,
            ],

            // Nabeul (2 clinics)
            [
                'name' => ['fr' => 'Clinique Nabeul Centre', 'ar' => 'عيادة نابل المركز', 'en' => 'Nabeul Center Clinic'],
                'code' => 'CLINIC-NAB-01',
                'email' => 'nabeul@clinicbooking.tn',
                'phone' => '+216 72 567 001',
                'address' => 'Avenue Habib Bourguiba',
                'city' => 'Nabeul',
                'postal_code' => '8000',
                'country' => 'Tunisia',
                'latitude' => 36.4516,
                'longitude' => 10.7361,
                'timezone' => 'Africa/Tunis',
                'working_hours' => $this->getStandardWorkingHours(),
                'is_active' => true,
            ],
            [
                'name' => ['fr' => 'Clinique Hammamet', 'ar' => 'عيادة الحمامات', 'en' => 'Hammamet Clinic'],
                'code' => 'CLINIC-NAB-02',
                'email' => 'hammamet@clinicbooking.tn',
                'phone' => '+216 72 567 002',
                'address' => 'Avenue de la République',
                'city' => 'Hammamet',
                'postal_code' => '8050',
                'country' => 'Tunisia',
                'latitude' => 36.4000,
                'longitude' => 10.6167,
                'timezone' => 'Africa/Tunis',
                'working_hours' => $this->getStandardWorkingHours(),
                'is_active' => true,
            ],

            // Zaghouan (2 clinics)
            [
                'name' => ['fr' => 'Clinique Zaghouan', 'ar' => 'عيادة زغوان', 'en' => 'Zaghouan Clinic'],
                'code' => 'CLINIC-ZAG-01',
                'email' => 'zaghouan@clinicbooking.tn',
                'phone' => '+216 72 678 001',
                'address' => 'Avenue Habib Bourguiba',
                'city' => 'Zaghouan',
                'postal_code' => '1100',
                'country' => 'Tunisia',
                'latitude' => 36.4028,
                'longitude' => 10.1425,
                'timezone' => 'Africa/Tunis',
                'working_hours' => $this->getStandardWorkingHours(),
                'is_active' => true,
            ],
            [
                'name' => ['fr' => 'Clinique Zaghouan Nord', 'ar' => 'عيادة زغوان الشمالية', 'en' => 'Zaghouan North Clinic'],
                'code' => 'CLINIC-ZAG-02',
                'email' => 'zaghouan.nord@clinicbooking.tn',
                'phone' => '+216 72 678 002',
                'address' => 'Route de Tunis',
                'city' => 'Zaghouan',
                'postal_code' => '1100',
                'country' => 'Tunisia',
                'latitude' => 36.4200,
                'longitude' => 10.1500,
                'timezone' => 'Africa/Tunis',
                'working_hours' => $this->getStandardWorkingHours(),
                'is_active' => true,
            ],

            // Bizerte (2 clinics)
            [
                'name' => ['fr' => 'Clinique Bizerte Centre', 'ar' => 'عيادة بنزرت المركز', 'en' => 'Bizerte Center Clinic'],
                'code' => 'CLINIC-BIZ-01',
                'email' => 'bizerte@clinicbooking.tn',
                'phone' => '+216 72 789 001',
                'address' => 'Avenue Habib Bourguiba',
                'city' => 'Bizerte',
                'postal_code' => '7000',
                'country' => 'Tunisia',
                'latitude' => 37.2744,
                'longitude' => 9.8739,
                'timezone' => 'Africa/Tunis',
                'working_hours' => $this->getStandardWorkingHours(),
                'is_active' => true,
            ],
            [
                'name' => ['fr' => 'Clinique Menzel Bourguiba', 'ar' => 'عيادة منزل بورقيبة', 'en' => 'Menzel Bourguiba Clinic'],
                'code' => 'CLINIC-BIZ-02',
                'email' => 'menzel@clinicbooking.tn',
                'phone' => '+216 72 789 002',
                'address' => 'Avenue de la République',
                'city' => 'Menzel Bourguiba',
                'postal_code' => '7050',
                'country' => 'Tunisia',
                'latitude' => 37.1544,
                'longitude' => 9.7856,
                'timezone' => 'Africa/Tunis',
                'working_hours' => $this->getStandardWorkingHours(),
                'is_active' => true,
            ],

            // Béja (2 clinics)
            [
                'name' => ['fr' => 'Clinique Béja', 'ar' => 'عيادة باجة', 'en' => 'Beja Clinic'],
                'code' => 'CLINIC-BEJ-01',
                'email' => 'beja@clinicbooking.tn',
                'phone' => '+216 78 890 001',
                'address' => 'Avenue Habib Bourguiba',
                'city' => 'Béja',
                'postal_code' => '9000',
                'country' => 'Tunisia',
                'latitude' => 36.7256,
                'longitude' => 9.1817,
                'timezone' => 'Africa/Tunis',
                'working_hours' => $this->getStandardWorkingHours(),
                'is_active' => true,
            ],
            [
                'name' => ['fr' => 'Clinique Béja Sud', 'ar' => 'عيادة باجة الجنوبية', 'en' => 'Beja South Clinic'],
                'code' => 'CLINIC-BEJ-02',
                'email' => 'beja.sud@clinicbooking.tn',
                'phone' => '+216 78 890 002',
                'address' => 'Route de Tunis',
                'city' => 'Béja',
                'postal_code' => '9000',
                'country' => 'Tunisia',
                'latitude' => 36.7100,
                'longitude' => 9.1900,
                'timezone' => 'Africa/Tunis',
                'working_hours' => $this->getStandardWorkingHours(),
                'is_active' => true,
            ],

            // Jendouba (2 clinics)
            [
                'name' => ['fr' => 'Clinique Jendouba', 'ar' => 'عيادة جندوبة', 'en' => 'Jendouba Clinic'],
                'code' => 'CLINIC-JEN-01',
                'email' => 'jendouba@clinicbooking.tn',
                'phone' => '+216 78 901 001',
                'address' => 'Avenue Habib Bourguiba',
                'city' => 'Jendouba',
                'postal_code' => '8100',
                'country' => 'Tunisia',
                'latitude' => 36.5011,
                'longitude' => 8.7803,
                'timezone' => 'Africa/Tunis',
                'working_hours' => $this->getStandardWorkingHours(),
                'is_active' => true,
            ],
            [
                'name' => ['fr' => 'Clinique Tabarka', 'ar' => 'عيادة طبرقة', 'en' => 'Tabarka Clinic'],
                'code' => 'CLINIC-JEN-02',
                'email' => 'tabarka@clinicbooking.tn',
                'phone' => '+216 78 901 002',
                'address' => 'Avenue Bourguiba',
                'city' => 'Tabarka',
                'postal_code' => '8110',
                'country' => 'Tunisia',
                'latitude' => 36.9544,
                'longitude' => 8.7581,
                'timezone' => 'Africa/Tunis',
                'working_hours' => $this->getStandardWorkingHours(),
                'is_active' => true,
            ],

            // Kef (2 clinics)
            [
                'name' => ['fr' => 'Clinique Kef', 'ar' => 'عيادة الكاف', 'en' => 'Kef Clinic'],
                'code' => 'CLINIC-KEF-01',
                'email' => 'kef@clinicbooking.tn',
                'phone' => '+216 78 012 001',
                'address' => 'Avenue Habib Bourguiba',
                'city' => 'Le Kef',
                'postal_code' => '7100',
                'country' => 'Tunisia',
                'latitude' => 36.1742,
                'longitude' => 8.7050,
                'timezone' => 'Africa/Tunis',
                'working_hours' => $this->getStandardWorkingHours(),
                'is_active' => true,
            ],
            [
                'name' => ['fr' => 'Clinique Kef Centre', 'ar' => 'عيادة الكاف المركز', 'en' => 'Kef Center Clinic'],
                'code' => 'CLINIC-KEF-02',
                'email' => 'kef.centre@clinicbooking.tn',
                'phone' => '+216 78 012 002',
                'address' => 'Place de l\'Indépendance',
                'city' => 'Le Kef',
                'postal_code' => '7100',
                'country' => 'Tunisia',
                'latitude' => 36.1800,
                'longitude' => 8.7100,
                'timezone' => 'Africa/Tunis',
                'working_hours' => $this->getStandardWorkingHours(),
                'is_active' => true,
            ],

            // Siliana (2 clinics)
            [
                'name' => ['fr' => 'Clinique Siliana', 'ar' => 'عيادة سليانة', 'en' => 'Siliana Clinic'],
                'code' => 'CLINIC-SIL-01',
                'email' => 'siliana@clinicbooking.tn',
                'phone' => '+216 78 123 001',
                'address' => 'Avenue Habib Bourguiba',
                'city' => 'Siliana',
                'postal_code' => '6100',
                'country' => 'Tunisia',
                'latitude' => 36.0850,
                'longitude' => 9.3706,
                'timezone' => 'Africa/Tunis',
                'working_hours' => $this->getStandardWorkingHours(),
                'is_active' => true,
            ],
            [
                'name' => ['fr' => 'Clinique Siliana Nord', 'ar' => 'عيادة سليانة الشمالية', 'en' => 'Siliana North Clinic'],
                'code' => 'CLINIC-SIL-02',
                'email' => 'siliana.nord@clinicbooking.tn',
                'phone' => '+216 78 123 002',
                'address' => 'Route de Tunis',
                'city' => 'Siliana',
                'postal_code' => '6100',
                'country' => 'Tunisia',
                'latitude' => 36.1000,
                'longitude' => 9.3800,
                'timezone' => 'Africa/Tunis',
                'working_hours' => $this->getStandardWorkingHours(),
                'is_active' => true,
            ],

            // Sousse (2 clinics)
            [
                'name' => ['fr' => 'Clinique Sousse Centre', 'ar' => 'عيادة سوسة المركز', 'en' => 'Sousse Center Clinic'],
                'code' => 'CLINIC-SOU-01',
                'email' => 'sousse@clinicbooking.tn',
                'phone' => '+216 73 234 001',
                'address' => 'Avenue Habib Bourguiba',
                'city' => 'Sousse',
                'postal_code' => '4000',
                'country' => 'Tunisia',
                'latitude' => 35.8256,
                'longitude' => 10.6369,
                'timezone' => 'Africa/Tunis',
                'working_hours' => $this->getStandardWorkingHours(),
                'is_active' => true,
            ],
            [
                'name' => ['fr' => 'Clinique Sahloul', 'ar' => 'عيادة سهلول', 'en' => 'Sahloul Clinic'],
                'code' => 'CLINIC-SOU-02',
                'email' => 'sahloul@clinicbooking.tn',
                'phone' => '+216 73 234 002',
                'address' => 'Route de la Corniche',
                'city' => 'Sousse',
                'postal_code' => '4054',
                'country' => 'Tunisia',
                'latitude' => 35.8400,
                'longitude' => 10.6100,
                'timezone' => 'Africa/Tunis',
                'working_hours' => $this->getStandardWorkingHours(),
                'is_active' => true,
            ],

            // Monastir (2 clinics)
            [
                'name' => ['fr' => 'Clinique Monastir Centre', 'ar' => 'عيادة المنستير المركز', 'en' => 'Monastir Center Clinic'],
                'code' => 'CLINIC-MON-01',
                'email' => 'monastir@clinicbooking.tn',
                'phone' => '+216 73 345 001',
                'address' => 'Avenue Habib Bourguiba',
                'city' => 'Monastir',
                'postal_code' => '5000',
                'country' => 'Tunisia',
                'latitude' => 35.7775,
                'longitude' => 10.8264,
                'timezone' => 'Africa/Tunis',
                'working_hours' => $this->getStandardWorkingHours(),
                'is_active' => true,
            ],
            [
                'name' => ['fr' => 'Clinique Skanes', 'ar' => 'عيادة سكانس', 'en' => 'Skanes Clinic'],
                'code' => 'CLINIC-MON-02',
                'email' => 'skanes@clinicbooking.tn',
                'phone' => '+216 73 345 002',
                'address' => 'Route Touristique',
                'city' => 'Monastir',
                'postal_code' => '5000',
                'country' => 'Tunisia',
                'latitude' => 35.7500,
                'longitude' => 10.8500,
                'timezone' => 'Africa/Tunis',
                'working_hours' => $this->getStandardWorkingHours(),
                'is_active' => true,
            ],

            // Mahdia (2 clinics)
            [
                'name' => ['fr' => 'Clinique Mahdia', 'ar' => 'عيادة المهدية', 'en' => 'Mahdia Clinic'],
                'code' => 'CLINIC-MAH-01',
                'email' => 'mahdia@clinicbooking.tn',
                'phone' => '+216 73 456 001',
                'address' => 'Avenue Habib Bourguiba',
                'city' => 'Mahdia',
                'postal_code' => '5100',
                'country' => 'Tunisia',
                'latitude' => 35.5047,
                'longitude' => 11.0622,
                'timezone' => 'Africa/Tunis',
                'working_hours' => $this->getStandardWorkingHours(),
                'is_active' => true,
            ],
            [
                'name' => ['fr' => 'Clinique Mahdia Port', 'ar' => 'عيادة ميناء المهدية', 'en' => 'Mahdia Port Clinic'],
                'code' => 'CLINIC-MAH-02',
                'email' => 'mahdia.port@clinicbooking.tn',
                'phone' => '+216 73 456 002',
                'address' => 'Zone Portuaire',
                'city' => 'Mahdia',
                'postal_code' => '5100',
                'country' => 'Tunisia',
                'latitude' => 35.5100,
                'longitude' => 11.0700,
                'timezone' => 'Africa/Tunis',
                'working_hours' => $this->getStandardWorkingHours(),
                'is_active' => true,
            ],

            // Sfax (2 clinics)
            [
                'name' => ['fr' => 'Clinique Sfax Centre', 'ar' => 'عيادة صفاقس المركز', 'en' => 'Sfax Center Clinic'],
                'code' => 'CLINIC-SFX-01',
                'email' => 'sfax@clinicbooking.tn',
                'phone' => '+216 74 567 001',
                'address' => 'Avenue Majida Boulila',
                'city' => 'Sfax',
                'postal_code' => '3000',
                'country' => 'Tunisia',
                'latitude' => 34.7406,
                'longitude' => 10.7603,
                'timezone' => 'Africa/Tunis',
                'working_hours' => $this->getStandardWorkingHours(),
                'is_active' => true,
            ],
            [
                'name' => ['fr' => 'Clinique Sfax El Jadida', 'ar' => 'عيادة صفاقس الجديدة', 'en' => 'Sfax New City Clinic'],
                'code' => 'CLINIC-SFX-02',
                'email' => 'sfax.jadida@clinicbooking.tn',
                'phone' => '+216 74 567 002',
                'address' => 'Route de Tunis',
                'city' => 'Sfax',
                'postal_code' => '3027',
                'country' => 'Tunisia',
                'latitude' => 34.7500,
                'longitude' => 10.7700,
                'timezone' => 'Africa/Tunis',
                'working_hours' => $this->getStandardWorkingHours(),
                'is_active' => true,
            ],

            // Kairouan (2 clinics)
            [
                'name' => ['fr' => 'Clinique Kairouan', 'ar' => 'عيادة القيروان', 'en' => 'Kairouan Clinic'],
                'code' => 'CLINIC-KAI-01',
                'email' => 'kairouan@clinicbooking.tn',
                'phone' => '+216 77 678 001',
                'address' => 'Avenue de la République',
                'city' => 'Kairouan',
                'postal_code' => '3100',
                'country' => 'Tunisia',
                'latitude' => 35.6781,
                'longitude' => 10.0967,
                'timezone' => 'Africa/Tunis',
                'working_hours' => $this->getStandardWorkingHours(),
                'is_active' => true,
            ],
            [
                'name' => ['fr' => 'Clinique Kairouan Nord', 'ar' => 'عيادة القيروان الشمالية', 'en' => 'Kairouan North Clinic'],
                'code' => 'CLINIC-KAI-02',
                'email' => 'kairouan.nord@clinicbooking.tn',
                'phone' => '+216 77 678 002',
                'address' => 'Route de Tunis',
                'city' => 'Kairouan',
                'postal_code' => '3100',
                'country' => 'Tunisia',
                'latitude' => 35.6900,
                'longitude' => 10.1000,
                'timezone' => 'Africa/Tunis',
                'working_hours' => $this->getStandardWorkingHours(),
                'is_active' => true,
            ],

            // Kasserine (2 clinics)
            [
                'name' => ['fr' => 'Clinique Kasserine', 'ar' => 'عيادة القصرين', 'en' => 'Kasserine Clinic'],
                'code' => 'CLINIC-KAS-01',
                'email' => 'kasserine@clinicbooking.tn',
                'phone' => '+216 77 789 001',
                'address' => 'Avenue Habib Bourguiba',
                'city' => 'Kasserine',
                'postal_code' => '1200',
                'country' => 'Tunisia',
                'latitude' => 35.1675,
                'longitude' => 8.8306,
                'timezone' => 'Africa/Tunis',
                'working_hours' => $this->getStandardWorkingHours(),
                'is_active' => true,
            ],
            [
                'name' => ['fr' => 'Clinique Kasserine Sud', 'ar' => 'عيادة القصرين الجنوبية', 'en' => 'Kasserine South Clinic'],
                'code' => 'CLINIC-KAS-02',
                'email' => 'kasserine.sud@clinicbooking.tn',
                'phone' => '+216 77 789 002',
                'address' => 'Route de Gafsa',
                'city' => 'Kasserine',
                'postal_code' => '1200',
                'country' => 'Tunisia',
                'latitude' => 35.1500,
                'longitude' => 8.8400,
                'timezone' => 'Africa/Tunis',
                'working_hours' => $this->getStandardWorkingHours(),
                'is_active' => true,
            ],

            // Sidi Bouzid (2 clinics)
            [
                'name' => ['fr' => 'Clinique Sidi Bouzid', 'ar' => 'عيادة سيدي بوزيد', 'en' => 'Sidi Bouzid Clinic'],
                'code' => 'CLINIC-SID-01',
                'email' => 'sidibouzid@clinicbooking.tn',
                'phone' => '+216 76 890 001',
                'address' => 'Avenue Habib Bourguiba',
                'city' => 'Sidi Bouzid',
                'postal_code' => '9100',
                'country' => 'Tunisia',
                'latitude' => 35.0381,
                'longitude' => 9.4858,
                'timezone' => 'Africa/Tunis',
                'working_hours' => $this->getStandardWorkingHours(),
                'is_active' => true,
            ],
            [
                'name' => ['fr' => 'Clinique Sidi Bouzid Centre', 'ar' => 'عيادة سيدي بوزيد المركز', 'en' => 'Sidi Bouzid Center Clinic'],
                'code' => 'CLINIC-SID-02',
                'email' => 'sidibouzid.centre@clinicbooking.tn',
                'phone' => '+216 76 890 002',
                'address' => 'Place de la République',
                'city' => 'Sidi Bouzid',
                'postal_code' => '9100',
                'country' => 'Tunisia',
                'latitude' => 35.0400,
                'longitude' => 9.4900,
                'timezone' => 'Africa/Tunis',
                'working_hours' => $this->getStandardWorkingHours(),
                'is_active' => true,
            ],

            // Gabès (2 clinics)
            [
                'name' => ['fr' => 'Clinique Gabès', 'ar' => 'عيادة قابس', 'en' => 'Gabes Clinic'],
                'code' => 'CLINIC-GAB-01',
                'email' => 'gabes@clinicbooking.tn',
                'phone' => '+216 75 901 001',
                'address' => 'Avenue Farhat Hached',
                'city' => 'Gabès',
                'postal_code' => '6000',
                'country' => 'Tunisia',
                'latitude' => 33.8815,
                'longitude' => 10.0982,
                'timezone' => 'Africa/Tunis',
                'working_hours' => $this->getStandardWorkingHours(),
                'is_active' => true,
            ],
            [
                'name' => ['fr' => 'Clinique Gabès Plage', 'ar' => 'عيادة شاطئ قابس', 'en' => 'Gabes Beach Clinic'],
                'code' => 'CLINIC-GAB-02',
                'email' => 'gabes.plage@clinicbooking.tn',
                'phone' => '+216 75 901 002',
                'address' => 'Route de la Plage',
                'city' => 'Gabès',
                'postal_code' => '6000',
                'country' => 'Tunisia',
                'latitude' => 33.8900,
                'longitude' => 10.1100,
                'timezone' => 'Africa/Tunis',
                'working_hours' => $this->getStandardWorkingHours(),
                'is_active' => true,
            ],

            // Medenine (2 clinics)
            [
                'name' => ['fr' => 'Clinique Medenine', 'ar' => 'عيادة مدنين', 'en' => 'Medenine Clinic'],
                'code' => 'CLINIC-MED-01',
                'email' => 'medenine@clinicbooking.tn',
                'phone' => '+216 75 012 001',
                'address' => 'Avenue Habib Bourguiba',
                'city' => 'Medenine',
                'postal_code' => '4100',
                'country' => 'Tunisia',
                'latitude' => 33.3547,
                'longitude' => 10.5053,
                'timezone' => 'Africa/Tunis',
                'working_hours' => $this->getStandardWorkingHours(),
                'is_active' => true,
            ],
            [
                'name' => ['fr' => 'Clinique Djerba', 'ar' => 'عيادة جربة', 'en' => 'Djerba Clinic'],
                'code' => 'CLINIC-MED-02',
                'email' => 'djerba@clinicbooking.tn',
                'phone' => '+216 75 012 002',
                'address' => 'Houmt Souk',
                'city' => 'Djerba',
                'postal_code' => '4180',
                'country' => 'Tunisia',
                'latitude' => 33.8753,
                'longitude' => 10.8578,
                'timezone' => 'Africa/Tunis',
                'working_hours' => $this->getStandardWorkingHours(),
                'is_active' => true,
            ],

            // Tataouine (2 clinics)
            [
                'name' => ['fr' => 'Clinique Tataouine', 'ar' => 'عيادة تطاوين', 'en' => 'Tataouine Clinic'],
                'code' => 'CLINIC-TAT-01',
                'email' => 'tataouine@clinicbooking.tn',
                'phone' => '+216 75 123 001',
                'address' => 'Avenue Habib Bourguiba',
                'city' => 'Tataouine',
                'postal_code' => '3200',
                'country' => 'Tunisia',
                'latitude' => 32.9297,
                'longitude' => 10.4517,
                'timezone' => 'Africa/Tunis',
                'working_hours' => $this->getStandardWorkingHours(),
                'is_active' => true,
            ],
            [
                'name' => ['fr' => 'Clinique Tataouine Nord', 'ar' => 'عيادة تطاوين الشمالية', 'en' => 'Tataouine North Clinic'],
                'code' => 'CLINIC-TAT-02',
                'email' => 'tataouine.nord@clinicbooking.tn',
                'phone' => '+216 75 123 002',
                'address' => 'Route de Medenine',
                'city' => 'Tataouine',
                'postal_code' => '3200',
                'country' => 'Tunisia',
                'latitude' => 32.9400,
                'longitude' => 10.4600,
                'timezone' => 'Africa/Tunis',
                'working_hours' => $this->getStandardWorkingHours(),
                'is_active' => true,
            ],

            // Gafsa (2 clinics)
            [
                'name' => ['fr' => 'Clinique Gafsa', 'ar' => 'عيادة قفصة', 'en' => 'Gafsa Clinic'],
                'code' => 'CLINIC-GAF-01',
                'email' => 'gafsa@clinicbooking.tn',
                'phone' => '+216 76 234 001',
                'address' => 'Avenue Habib Bourguiba',
                'city' => 'Gafsa',
                'postal_code' => '2100',
                'country' => 'Tunisia',
                'latitude' => 34.4250,
                'longitude' => 8.7842,
                'timezone' => 'Africa/Tunis',
                'working_hours' => $this->getStandardWorkingHours(),
                'is_active' => true,
            ],
            [
                'name' => ['fr' => 'Clinique Gafsa Centre', 'ar' => 'عيادة قفصة المركز', 'en' => 'Gafsa Center Clinic'],
                'code' => 'CLINIC-GAF-02',
                'email' => 'gafsa.centre@clinicbooking.tn',
                'phone' => '+216 76 234 002',
                'address' => 'Place de la République',
                'city' => 'Gafsa',
                'postal_code' => '2100',
                'country' => 'Tunisia',
                'latitude' => 34.4300,
                'longitude' => 8.7900,
                'timezone' => 'Africa/Tunis',
                'working_hours' => $this->getStandardWorkingHours(),
                'is_active' => true,
            ],

            // Tozeur (2 clinics)
            [
                'name' => ['fr' => 'Clinique Tozeur', 'ar' => 'عيادة توزر', 'en' => 'Tozeur Clinic'],
                'code' => 'CLINIC-TOZ-01',
                'email' => 'tozeur@clinicbooking.tn',
                'phone' => '+216 76 345 001',
                'address' => 'Avenue Habib Bourguiba',
                'city' => 'Tozeur',
                'postal_code' => '2200',
                'country' => 'Tunisia',
                'latitude' => 33.9197,
                'longitude' => 8.1339,
                'timezone' => 'Africa/Tunis',
                'working_hours' => $this->getStandardWorkingHours(),
                'is_active' => true,
            ],
            [
                'name' => ['fr' => 'Clinique Nefta', 'ar' => 'عيادة نفطة', 'en' => 'Nefta Clinic'],
                'code' => 'CLINIC-TOZ-02',
                'email' => 'nefta@clinicbooking.tn',
                'phone' => '+216 76 345 002',
                'address' => 'Centre Ville',
                'city' => 'Nefta',
                'postal_code' => '2240',
                'country' => 'Tunisia',
                'latitude' => 33.8731,
                'longitude' => 7.8778,
                'timezone' => 'Africa/Tunis',
                'working_hours' => $this->getStandardWorkingHours(),
                'is_active' => true,
            ],

            // Kebili (2 clinics)
            [
                'name' => ['fr' => 'Clinique Kebili', 'ar' => 'عيادة قبلي', 'en' => 'Kebili Clinic'],
                'code' => 'CLINIC-KEB-01',
                'email' => 'kebili@clinicbooking.tn',
                'phone' => '+216 75 456 001',
                'address' => 'Avenue Habib Bourguiba',
                'city' => 'Kebili',
                'postal_code' => '4200',
                'country' => 'Tunisia',
                'latitude' => 33.7047,
                'longitude' => 8.9697,
                'timezone' => 'Africa/Tunis',
                'working_hours' => $this->getStandardWorkingHours(),
                'is_active' => true,
            ],
            [
                'name' => ['fr' => 'Clinique Douz', 'ar' => 'عيادة دوز', 'en' => 'Douz Clinic'],
                'code' => 'CLINIC-KEB-02',
                'email' => 'douz@clinicbooking.tn',
                'phone' => '+216 75 456 002',
                'address' => 'Centre Ville',
                'city' => 'Douz',
                'postal_code' => '4260',
                'country' => 'Tunisia',
                'latitude' => 33.4667,
                'longitude' => 9.0167,
                'timezone' => 'Africa/Tunis',
                'working_hours' => $this->getStandardWorkingHours(),
                'is_active' => true,
            ],
        ];
    }

    private function getStandardWorkingHours(): array
    {
        return [
            'monday' => ['start' => '08:00', 'end' => '18:00'],
            'tuesday' => ['start' => '08:00', 'end' => '18:00'],
            'wednesday' => ['start' => '08:00', 'end' => '18:00'],
            'thursday' => ['start' => '08:00', 'end' => '18:00'],
            'friday' => ['start' => '08:00', 'end' => '18:00'],
            'saturday' => ['start' => '08:00', 'end' => '13:00'],
            'sunday' => null,
        ];
    }
}
